sonar.projectKey=Onoiro_TaskMan
sonar.organization=abo

# path to test coverage report
sonar.python.coverage.reportPaths=coverage.xml

sonar.coverage.exclusions=**/migrations/**/*, manage.py, **/settings.py, **/settings_*.py, **/apps.py, **/wsgi.py, **/asgi.py, **/tests/**/*

# optional
sonar.sources=task_manager
sonar.language=python

# exclude CPD - Copy Paste Detector only for templates
sonar.cpd.exclusions=**/templates/**/*.html
