# Generated by Django 4.2.13 on 2024-11-25 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(
                    primary_key=True,
                    serialize=False)),
                ('name', models.CharField(
                    max_length=150,
                    unique=True,
                    verbose_name='Name')),
                ('description', models.TextField(
                    blank=True,
                    verbose_name='Description')),
                ('created_at', models.DateTimeField(
                    auto_now_add=True,
                    verbose_name='Created at')),
            ],
        ),
    ]
