# Generated by Django 5.2.9 on 2026-03-01 16:36

from django.db import migrations, models


def set_existing_members_active(apps, schema_editor):
    """Set all existing memberships to active status."""
    TeamMembership = apps.get_model('teams', 'TeamMembership')
    TeamMembership.objects.all().update(status='active')


def reverse_func(apps, schema_editor):
    """Reverse operation - set all to pending."""
    TeamMembership = apps.get_model('teams', 'TeamMembership')
    TeamMembership.objects.all().update(status='pending')


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammembership',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('active', 'Active')], default='active', max_length=10),
        ),
        # Set existing members to active
        migrations.RunPython(set_existing_members_active, reverse_func),
    ]
