# Generated by Django 5.2.9 on 2026-01-02 22:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='members',
            field=models.ManyToManyField(
                related_name='member_teams',
                through='teams.TeamMembership',
                through_fields=('team', 'user'),
                to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
