# Generated by Django 4.2.13 on 2025-04-16 21:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='password',
            field=models.CharField(
                help_text='Minimum length is 3 characters',
                max_length=128,
                null=True,
                validators=[django.core.validators.MinLengthValidator(3)],
                verbose_name='Team password'),
        ),
    ]
