# Generated by Django 5.2.9 on 2026-04-03 16:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0003_teammembership_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='description',
            field=models.TextField(blank=True, validators=[django.core.validators.MaxLengthValidator(20000)], verbose_name='Description'),
        ),
    ]
