# Generated by Django 5.2.9 on 2026-05-11 20:40

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0004_alter_team_description'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamInvite',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('invite_code', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='Invite code')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('expires_at', models.DateTimeField(verbose_name='Expires at')),
                ('is_used', models.BooleanField(default=False, verbose_name='Is used')),
                ('used_at', models.DateTimeField(blank=True, null=True, verbose_name='Used at')),
                ('max_uses', models.IntegerField(default=1, help_text='Number of times invite can be used', verbose_name='Max uses')),
                ('use_count', models.IntegerField(default=0, verbose_name='Use count')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_invites', to=settings.AUTH_USER_MODEL)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invites', to='teams.team')),
                ('used_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='used_invites', to=settings.AUTH_USER_MODEL, verbose_name='Used by')),
            ],
            options={
                'verbose_name': 'Team invite',
                'verbose_name_plural': 'Team invites',
                'ordering': ['-created_at'],
            },
        ),
    ]
