# Generated by Django 4.2.13 on 2025-05-29 20:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0004_alter_team_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='password',
            field=models.CharField(
                help_text='Minimum length is 3 characters',
                max_length=128,
                validators=[django.core.validators.MinLengthValidator(3)],
                verbose_name='Team password'
            ),
        ),
    ]
