# Generated by Django 4.2.13 on 2025-05-29 20:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('labels', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='label',
            name='creator',
            field=models.ForeignKey(
                default='26',
                on_delete=django.db.models.deletion.CASCADE,
                related_name='created_labels',
                to=settings.AUTH_USER_MODEL
            ),
            preserve_default=False,
        ),
    ]
