# Generated by Django 6.0.5 on 2026-05-23 18:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('task_assigned', 'Task assigned'), ('task_unassigned', 'Task unassigned'), ('task_status_changed', 'Task status changed'), ('task_completed', 'Task completed'), ('team_join_request', 'Team join request'), ('team_member_joined', 'Team member joined'), ('team_request_approved', 'Team request approved'), ('team_request_rejected', 'Team request rejected'), ('team_member_removed', 'Team member removed'), ('team_role_changed', 'Team role changed'), ('team_invited', 'Team invited'), ('team_deleted', 'Team deleted')], max_length=30, verbose_name='Notification type')),
                ('message', models.TextField(verbose_name='Message')),
                ('action_url', models.CharField(blank=True, max_length=500, verbose_name='Action URL')),
                ('is_read', models.BooleanField(default=False, verbose_name='Is read')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='Recipient')),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['recipient', 'is_read', 'created_at'], name='notif_recip_read_created_idx')],
            },
        ),
    ]
