# Generated by Django 6.0.5 on 2026-05-25 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='message_key',
            field=models.CharField(blank=True, help_text='Translation key for the message template.', max_length=50, verbose_name='Message key'),
        ),
        migrations.AddField(
            model_name='notification',
            name='message_params',
            field=models.JSONField(blank=True, default=dict, help_text='JSON parameters for message template.', verbose_name='Message parameters'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='message',
            field=models.TextField(blank=True, help_text='Legacy field. Use message_key and message_params for new notifications.', verbose_name='Message'),
        ),
    ]
