# Generated by Django 6.0.5 on 2026-06-15 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_notification_message_key_notification_message_params_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='message_key',
            field=models.CharField(blank=True, help_text='Translation key for the message template.', max_length=255, verbose_name='Message key'),
        ),
    ]
