# Generated by Django 6.0.5 on 2026-09-16 15:30

import django.db.models.deletion
import task_manager.notes.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_alter_note_content_alter_note_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='NoteImage',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to=task_manager.notes.models.note_image_upload_to, verbose_name='Image')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Order')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Uploaded at')),
                ('note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='notes.note', verbose_name='Note')),
            ],
            options={
                'verbose_name': 'Note image',
                'verbose_name_plural': 'Note images',
                'ordering': ['order', 'id'],
            },
        ),
    ]
