# Generated by Django 6.0.5 on 2026-09-28 21:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0003_noteimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='content',
            field=models.TextField(blank=True, validators=[django.core.validators.MaxLengthValidator(20000)], verbose_name='Content'),
        ),
    ]
