# Generated by Django 5.2.9 on 2026-04-03 16:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_user_deleted_at_user_is_deleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='description',
            field=models.TextField(blank=True, default='', validators=[django.core.validators.MaxLengthValidator(20000)], verbose_name='Description'),
        ),
    ]
