# Generated by Django 4.2.7 on 2024-03-22 22:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_rename_id_user_id_remove_user_fullname_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
