# Generated by Django 4.2.23 on 2025-09-02 21:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tasks', '0001_initial'),
        ('labels', '0002_initial'),
        ('statuses', '0002_initial'),
        migrations.swappable_dependency(
            settings.AUTH_USER_MODEL
        ),
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='author',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name='author_set',
                to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name='task',
            name='executor',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name='executor_set',
                to=settings.AUTH_USER_MODEL,
                verbose_name='Executor'
            ),
        ),
        migrations.AddField(
            model_name='task',
            name='labels',
            field=models.ManyToManyField(
                blank=True,
                to='labels.label',
                verbose_name='Labels'
            ),
        ),
        migrations.AddField(
            model_name='task',
            name='status',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to='statuses.status',
                verbose_name='Status'
            ),
        ),
        migrations.AddField(
            model_name='task',
            name='team',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='tasks',
                to='teams.team',
                verbose_name='Team'
            ),
        ),
    ]
