# Generated by Django 4.2.23 on 2025-07-10 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_task_labels'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='name',
            field=models.CharField(max_length=150, verbose_name='Name'),
        ),
    ]
