# Generated by Django 5.2.9 on 2026-02-24 20:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='executor',
        ),
        migrations.AddField(
            model_name='task',
            name='executors',
            field=models.ManyToManyField(blank=True, related_name='executor_tasks', to=settings.AUTH_USER_MODEL, verbose_name='Executors'),
        ),
    ]
