# Generated by Django 4.2.23 on 2025-07-29 22:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_alter_task_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='name',
            field=models.CharField(
                max_length=150,
                validators=[
                    django.core.validators.RegexValidator(
                        '^[\\w \\-:,.!?]+$',
                        message='Only letters, numbers, spaces, and '
                        '-_.,!? symbols are allowed. '
                        'Symbols <, >, #, & are not allowed.'
                    )
                ],
                verbose_name='Name'
            ),
        ),
    ]
