# Generated by Django 5.2.9 on 2026-03-06 21:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_executors'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChecklistItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=300, verbose_name='Text')),
                ('is_done', models.BooleanField(default=False, verbose_name='Done')),
                ('position', models.PositiveIntegerField(default=0, verbose_name='Position')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklist_items', to='tasks.task', verbose_name='Task')),
            ],
            options={
                'ordering': ['position', 'id'],
            },
        ),
    ]
