name: Abo check

on:
 - push

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11"]

    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      
      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip install poetry
          poetry install
      
      - name: Lint with flake8
        run: |
          make lint
        continue-on-error: true
      
      # - name: Проверка установленных секретов
      #   run: echo "CC_TEST_REPORTER_ID=$CC_TEST_REPORTER_ID"
      #   env:
      #     DATABASE_URL: sqlite:///db.sqlite3
      #     CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
      
      - name: test with unittest & test coverage
        run: |
          make test
        # will change it to postgres on render later
        env:
          DATABASE_URL: sqlite:///db.sqlite3
        
      - name: Publish code coverage
        uses: paambaati/codeclimate-action@v3.2.0
        env:
          # will change this line to postgres on render later
          DATABASE_URL: sqlite:///db.sqlite3
          CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
        with:
          coverageCommand: make cov
          debug: true
      