name: Abo check

on:
 - push

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11"]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip install poetry
          poetry install
      - name: Lint with flake8
        run: |
          make lint
        continue-on-error: true
      - name: test with unittest
        run: |
          make test
        # will change it tp postgres on render later
        env:
          DATABASE_URL: sqlite:///db.sqlite3