# Generated by Django 4.2.7 on 2024-03-22 22:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Statuses',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('status_name', models.CharField(
                    max_length=150,
                    unique=True,
                    validators=[
                        django.core.validators.RegexValidator('^[a-zA-Z0-9]'),
                        django.core.validators.MinLengthValidator(2)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
