# Generated by Django 4.2.7 on 2024-03-26 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('statuses', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='statuses',
            old_name='status_name',
            new_name='name',
        ),
    ]
