# Generated by Django 4.2.23 on 2025-10-23 20:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('statuses', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='creator',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='created_statuses',
                to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
