# Generated by Django 4.2.7 on 2024-03-29 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('statuses', '0003_rename_statuses_statuse'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Statuse',
            new_name='Status',
        ),
    ]
