# Generated by Django 6.0.5 on 2026-09-15 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statuses', '0003_alter_status_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='status',
            name='is_completed',
            field=models.BooleanField(default=False, help_text='Tasks with a final status are hidden from the default task list', verbose_name='Final status'),
        ),
    ]
