# Generated by Django 4.2.23 on 2025-11-04 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statuses', '0003_alter_status_creator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='description',
            field=models.TextField(
                blank=True,
                default='',
                verbose_name='Description'
            ),
            preserve_default=False,
        ),
    ]
