# Generated by Django 4.2.23 on 2025-07-10 21:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statuses', '0005_status_creator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='name',
            field=models.CharField(
                max_length=150,
                validators=[
                    django.core.validators.RegexValidator('^[a-zA-Z0-9]'),
                    django.core.validators.MinLengthValidator(2)
                ]
            ),
        ),
    ]
