# Generated by Django 4.2.23 on 2025-08-07 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statuses', '0007_alter_status_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='status',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
