# Generated by Django 4.2.23 on 2025-08-07 09:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statuses', '0008_status_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='created_at',
            field=models.DateTimeField(
                auto_now_add=True,
                verbose_name='Created at'
            ),
        ),
        migrations.AlterField(
            model_name='status',
            name='description',
            field=models.TextField(
                blank=True,
                null=True,
                verbose_name='Description'
            ),
        ),
        migrations.AlterField(
            model_name='status',
            name='name',
            field=models.CharField(
                max_length=24,
                validators=[
                    django.core.validators.RegexValidator(
                        '^[\\w \\-:,.!?]+$',
                        message='Only letters, numbers, spaces, and '
                        '-_.,!? symbols are allowed. Symbols <, >, #, '
                        '& are not allowed.'
                    )
                ], verbose_name='Name'
            ),
        ),
    ]
